# Generated by Django 3.2 on 2022-05-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_note_mag', '0003_auto_20220516_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='Music', max_length=50),
        ),
    ]
